### ISSUE TITLE
Complete upgrade to Lagom 1.5.x

### ISSUE THREAD

**Issue by ignasi35** [lagom/shopping-cart-scala#13]
There's a few small things to complete before considering the migration to Lagom 1.5.0 done:

- [x] check the dependency `lagom-scaladsl-akka-discovery-service-locator` is using latest
- [x] Remove explicit dependencies to akka-management (note dependency to `akka-discovery-kubernetes-api ` must remain)
- [ ] review README and remove any feature handled by lagom out of the box
- [x] review if [`akka.io.dns.resolver`](https://github.com/lagom/shopping-cart-scala/blob/1.4.x/inventory-impl/src/main/resources/prod-application.conf#L13) is still necessary (both Inventory's `application.conf` and Shopping-Cart's `application.conf`)
- [x] remove [`akka.management.http.route-providers`](https://github.com/lagom/shopping-cart-scala/blob/1.4.x/shopping-cart-impl/src/main/resources/prod-application.conf#L43)

**Comment by ignasi35** [comment]
We should also remove the manual handling of Akka extensions:

https://github.com/lagom/shopping-cart-scala/blob/1.4.x/shopping-cart/src/main/scala/com/example/shoppingcart/impl/ShoppingCartLoader.scala#L19-L20

**Comment by jroper** [comment]
#22 is also necessary for this, removing the now non existent `kubernetes-api.pod-port-name` configuration option.

**Comment by octonato** [comment]
It's done
