### ISSUE TITLE
Prefer using async-dns ?

### ISSUE THREAD

**Issue by ignasi35** [lagom/shopping-cart-scala#16]
The services in this sample app use use the [default resolver of `akka-dns`](https://doc.akka.io/docs/akka/current/io-dns.html#dns-extension).

The advantage is that it's a resolver that takes `/etc/resolv.conf` into consideration. The disadvantages are that it's blocking and doesn't support `SRV` lookups.

`async-dns`, OTOH, is asynchronous, supports `SRV` but ignores `Local hosts file`.

**Comment by TimMoore** [comment]
Service discovery always uses async-dns, even if that's not set as the default resolver. See https://github.com/akka/akka/pull/25937 for the change.

I don't think it's a good idea to set async-dns as the default in examples. It's still subject to change, has some known limitations, and has bitten customers in practice (back when it was required to set it to use DNS discovery).

**Comment by ignasi35** [comment]
Ah, I see my confusion now. Closing
